[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
gxhash = "3.4.1"
itertools = "0.13.0"
num = "0.4.3"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"
indoc = "2.0.5"
